### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by xspeed1989** [ac3ss0r/obfusheader.h#1]
Visual studio 2022
a.obj : error LNK2005: "void (__cdecl* obf::draw)(char const *)" (?draw@obf@@3P6AXPEBD@ZEA) already defined in b.obj

**Comment by ac3ss0r** [comment]
The problem is either because your compiler doesn't support #pragma once, or because you used namespace obf:: and the draw from it is conflicting with another method from your project. 
I replaced #pragma once with include guard, changed the draw method name to a less conflicting one
https://github.com/ac3ss0r/obfusheader.h/commit/85f741e236eb2dcfd32d12801d0e1c34d277a4b7
The issue should be resolved now, if it's not reopen it with more information
